### ISSUE TITLE
Баг при чистой версии DLE + Плагин

### ISSUE THREAD

**Issue by p1negin** [DLEPremium/kinopoisk-parser-dle#1]
Если нет папки /uploads/posts/2022-10 (тут от месяца и года зависит папка), то парсить не будет ничего - добавьте в функционал чтобы если нет папки то создавалась mkdir добавить не трудно)

**Comment by DLEPremium** [comment]
> Если нет папки /uploads/posts/2022-10 (тут от месяца и года зависит папка), то парсить не будет ничего - добавьте в функционал чтобы если нет папки то создавалась mkdir добавить не трудно)

Исправлено
