### ISSUE TITLE
На DLE 15.3 не сохраняет новые категории после парсинга

### ISSUE THREAD

**Issue by MGHaze** [DLEPremium/kinopoisk-parser-dle#2]
На DLE 15.3 (пробовал на разных версиях PHP) не сохраняет спарсенные категории, если ранее у новости уже было больше одной категории.

Что делаю:
1. Добавляю новость и 2 рандомные категории. Сохраняю новость.
2. Захожу в редактирование, парсю модулем по КП ID (например, 1320559). Все поля заполняются, категории сериала добавляются. Сохраняю новость.
3. Захожу в новость, а у новости все теже 2 рандомных категории. Новые не сохранились. Остальная инфа сохранилась.

Если у новости была одна категория, то новые сохраняются нормально.

**Comment by DLEPremium** [comment]
> На DLE 15.3 (пробовал на разных версиях PHP) не сохраняет спарсенные категории, если ранее у новости уже было больше одной категории.
> 
> Что делаю:
> 
> 1. Добавляю новость и 2 рандомные категории. Сохраняю новость.
> 2. Захожу в редактирование, парсю модулем по КП ID (например, 1320559). Все поля заполняются, категории сериала добавляются. Сохраняю новость.
> 3. Захожу в новость, а у новости все теже 2 рандомных категории. Новые не сохранились. Остальная инфа сохранилась.
> 
> Если у новости была одна категория, то новые сохраняются нормально.

Понял в чем дело, проблема была в hidden input с именем category_custom_sort, отвечающим за порядок сортировки категорий при сохранении. Исправлено
